// <auto-generated />
using System;
using HueFestival.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HueFestival.Migrations
{
    [DbContext(typeof(HueFestival_DbContext))]
    [Migration("20230615025634_updateDB2")]
    partial class updateDB2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HueFestival.Models.Account", b =>
                {
                    b.Property<int>("IdAcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAcc"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdAcc");

                    b.HasIndex("IdChucVu");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("HueFestival.Models.Check_in", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDatVe")
                        .HasColumnType("int");

                    b.Property<int>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCheckIn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Check_in");
                });

            modelBuilder.Entity("HueFestival.Models.ChiTiet_CTr", b =>
                {
                    b.Property<int>("IdChiTiet_Ctr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChiTiet_Ctr"));

                    b.Property<int>("IdCTr")
                        .HasColumnType("int");

                    b.Property<int>("IdDiaDiem")
                        .HasColumnType("int");

                    b.Property<int?>("IdDoan")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("IdNhomCTr")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<DateTime>("fDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("tDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdChiTiet_Ctr");

                    b.HasIndex("IdCTr");

                    b.HasIndex("IdDiaDiem");

                    b.HasIndex("IdDoan");

                    b.HasIndex("IdNhomCTr");

                    b.ToTable("ChiTiet_CTr");
                });

            modelBuilder.Entity("HueFestival.Models.ChiTiet_DatVe", b =>
                {
                    b.Property<int>("IdDatVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDatVe"));

                    b.Property<int>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("IdVe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("QRcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SLgVe")
                        .HasColumnType("int");

                    b.Property<int?>("ThanhTien")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("IdDatVe");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdVe")
                        .IsUnique();

                    b.ToTable("ChiTiet_DatVe");
                });

            modelBuilder.Entity("HueFestival.Models.ChucVu", b =>
                {
                    b.Property<int>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChucVu"));

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("HueFestival.Models.ChuongTrinh", b =>
                {
                    b.Property<int>("IdCTr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCTr"));

                    b.Property<int>("Arrange")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenCtr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeInOff")
                        .HasColumnType("int");

                    b.HasKey("IdCTr");

                    b.ToTable("ChuongTrinh");
                });

            modelBuilder.Entity("HueFestival.Models.DiaDiem", b =>
                {
                    b.Property<int>("IdDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiaDiem"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLoai_DD")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("ToaDoX")
                        .HasColumnType("float");

                    b.Property<double?>("ToaDoY")
                        .HasColumnType("float");

                    b.HasKey("IdDiaDiem");

                    b.HasIndex("IdLoai_DD");

                    b.ToTable("DiaDiem");
                });

            modelBuilder.Entity("HueFestival.Models.DoanNT", b =>
                {
                    b.Property<int>("IdDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDoan"));

                    b.Property<string>("TenDoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDoan");

                    b.ToTable("DoanNT");
                });

            modelBuilder.Entity("HueFestival.Models.HinhAnh_CTr", b =>
                {
                    b.Property<int>("IdHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHinhAnh"));

                    b.Property<int>("IdCTr")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHinhAnh");

                    b.HasIndex("IdCTr");

                    b.ToTable("HinhAnh_CTr");
                });

            modelBuilder.Entity("HueFestival.Models.HoTro", b =>
                {
                    b.Property<int>("IdHoTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoTro"));

                    b.Property<string>("HoTroName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHoTro");

                    b.ToTable("HoTro");
                });

            modelBuilder.Entity("HueFestival.Models.KhachHang", b =>
                {
                    b.Property<int>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhachHang"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("HueFestival.Models.Loai_DiaDiem", b =>
                {
                    b.Property<int>("IdLoai_DD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoai_DD"));

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuaDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLoai_DD");

                    b.ToTable("Loai_DiaDiem");
                });

            modelBuilder.Entity("HueFestival.Models.Loai_Ve", b =>
                {
                    b.Property<int>("IdLoai_Ve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoai_Ve"));

                    b.Property<string>("LoaiVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLoai_Ve");

                    b.ToTable("Loai_Ve");
                });

            modelBuilder.Entity("HueFestival.Models.Nhom_CTr", b =>
                {
                    b.Property<int>("IdNhomCTr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhomCTr"));

                    b.Property<string>("TenNhom_CTr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNhomCTr");

                    b.ToTable("Nhom_CTr");
                });

            modelBuilder.Entity("HueFestival.Models.ThongTin_Ve", b =>
                {
                    b.Property<int>("IdVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVe"));

                    b.Property<int>("GiaVe")
                        .HasColumnType("int");

                    b.Property<int>("IdCTr")
                        .HasColumnType("int");

                    b.Property<int>("IdLoai_Ve")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayPhatHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SLg")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdVe");

                    b.HasIndex("IdCTr");

                    b.HasIndex("IdLoai_Ve");

                    b.ToTable("ThongTin_Ve");
                });

            modelBuilder.Entity("HueFestival.Models.TinTuc", b =>
                {
                    b.Property<int>("IdTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTinTuc"));

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TuaDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTinTuc");

                    b.ToTable("TinTuc");
                });

            modelBuilder.Entity("HueFestival.Models.Account", b =>
                {
                    b.HasOne("HueFestival.Models.ChucVu", "ChucVus")
                        .WithMany()
                        .HasForeignKey("IdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVus");
                });

            modelBuilder.Entity("HueFestival.Models.ChiTiet_CTr", b =>
                {
                    b.HasOne("HueFestival.Models.ChuongTrinh", "ChuongTrinhs")
                        .WithMany("ChiTiet_CTrs")
                        .HasForeignKey("IdCTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.DiaDiem", "DiaDiems")
                        .WithMany()
                        .HasForeignKey("IdDiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.DoanNT", "DoanNTs")
                        .WithMany()
                        .HasForeignKey("IdDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.Nhom_CTr", "Nhom_CTrs")
                        .WithMany()
                        .HasForeignKey("IdNhomCTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhs");

                    b.Navigation("DiaDiems");

                    b.Navigation("DoanNTs");

                    b.Navigation("Nhom_CTrs");
                });

            modelBuilder.Entity("HueFestival.Models.ChiTiet_DatVe", b =>
                {
                    b.HasOne("HueFestival.Models.KhachHang", "KhachHangs")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.ThongTin_Ve", "ThongTin_Ves")
                        .WithOne("ChiTiet_DatVes")
                        .HasForeignKey("HueFestival.Models.ChiTiet_DatVe", "IdVe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHangs");

                    b.Navigation("ThongTin_Ves");
                });

            modelBuilder.Entity("HueFestival.Models.DiaDiem", b =>
                {
                    b.HasOne("HueFestival.Models.Loai_DiaDiem", "Loai_DiaDiems")
                        .WithMany()
                        .HasForeignKey("IdLoai_DD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loai_DiaDiems");
                });

            modelBuilder.Entity("HueFestival.Models.HinhAnh_CTr", b =>
                {
                    b.HasOne("HueFestival.Models.ChuongTrinh", "ChuongTrinhs")
                        .WithMany("HinhAnh_CTrs")
                        .HasForeignKey("IdCTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhs");
                });

            modelBuilder.Entity("HueFestival.Models.ThongTin_Ve", b =>
                {
                    b.HasOne("HueFestival.Models.ChuongTrinh", "ChuongTrinhs")
                        .WithMany("ThongTin_Ves")
                        .HasForeignKey("IdCTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.Loai_Ve", "Loai_Ves")
                        .WithMany()
                        .HasForeignKey("IdLoai_Ve")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhs");

                    b.Navigation("Loai_Ves");
                });

            modelBuilder.Entity("HueFestival.Models.ChuongTrinh", b =>
                {
                    b.Navigation("ChiTiet_CTrs");

                    b.Navigation("HinhAnh_CTrs");

                    b.Navigation("ThongTin_Ves");
                });

            modelBuilder.Entity("HueFestival.Models.ThongTin_Ve", b =>
                {
                    b.Navigation("ChiTiet_DatVes")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
