// <auto-generated />
using System;
using HueFestival.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HueFestival.Migrations
{
    [DbContext(typeof(HueFestival_DbContext))]
    [Migration("20230524190356_initDatabase")]
    partial class initDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HueFestival.Models.ChiTiet_CTr", b =>
                {
                    b.Property<int>("IdChiTiet_Ctr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChiTiet_Ctr"));

                    b.Property<int>("ChuongTrinhsIdCTr")
                        .HasColumnType("int");

                    b.Property<int>("DiaDiemsIdDiaDiem")
                        .HasColumnType("int");

                    b.Property<int>("DoanNTsIdDoan")
                        .HasColumnType("int");

                    b.Property<int>("IdCtr")
                        .HasColumnType("int");

                    b.Property<int>("IdDiaDiem")
                        .HasColumnType("int");

                    b.Property<int?>("IdDoan")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("IdNhomCTr")
                        .HasColumnType("int");

                    b.Property<int>("Nhom_CTrsIdNhomCTr")
                        .HasColumnType("int");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<DateTime>("fDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("tDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdChiTiet_Ctr");

                    b.HasIndex("ChuongTrinhsIdCTr");

                    b.HasIndex("DiaDiemsIdDiaDiem");

                    b.HasIndex("DoanNTsIdDoan");

                    b.HasIndex("Nhom_CTrsIdNhomCTr");

                    b.ToTable("ChiTiet_CTrs");
                });

            modelBuilder.Entity("HueFestival.Models.ChiTiet_DatVe", b =>
                {
                    b.Property<int>("IdDatVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDatVe"));

                    b.Property<int>("IdVe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDatVe");

                    b.ToTable("ChiTiet_DatVes");
                });

            modelBuilder.Entity("HueFestival.Models.ChuongTrinh", b =>
                {
                    b.Property<int>("IdCTr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCTr"));

                    b.Property<int>("Arrange")
                        .HasColumnType("int");

                    b.Property<double>("GiaTien")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCtr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeInOff")
                        .HasColumnType("int");

                    b.HasKey("IdCTr");

                    b.ToTable("ChuongTrinhs");
                });

            modelBuilder.Entity("HueFestival.Models.DiaDiem", b =>
                {
                    b.Property<int>("IdDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiaDiem"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLoaiDD")
                        .HasColumnType("int");

                    b.Property<int>("LoaiDiaDiemsIdLoaiDD")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("ToaDoX")
                        .HasColumnType("float");

                    b.Property<double>("ToaDoY")
                        .HasColumnType("float");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDiaDiem");

                    b.HasIndex("LoaiDiaDiemsIdLoaiDD");

                    b.ToTable("DiaDiems");
                });

            modelBuilder.Entity("HueFestival.Models.DoanNT", b =>
                {
                    b.Property<int>("IdDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDoan"));

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TuaDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDoan");

                    b.ToTable("DoanNTs");
                });

            modelBuilder.Entity("HueFestival.Models.HinhAnh_CTr", b =>
                {
                    b.Property<int>("IdHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHinhAnh"));

                    b.Property<int>("ChuongTrinhsIdCTr")
                        .HasColumnType("int");

                    b.Property<int>("IdCtr")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHinhAnh");

                    b.HasIndex("ChuongTrinhsIdCTr");

                    b.ToTable("HinhAnh_CTrs");
                });

            modelBuilder.Entity("HueFestival.Models.HoTro", b =>
                {
                    b.Property<int>("IdHoTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoTro"));

                    b.Property<string>("HoTroName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHoTro");

                    b.ToTable("HoTros");
                });

            modelBuilder.Entity("HueFestival.Models.LoaiDiaDiem", b =>
                {
                    b.Property<int>("IdLoaiDD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoaiDD"));

                    b.Property<int>("ChiTiet_CTrsIdChiTiet_Ctr")
                        .HasColumnType("int");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuaDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLoaiDD");

                    b.HasIndex("ChiTiet_CTrsIdChiTiet_Ctr");

                    b.ToTable("LoaiDiaDiems");
                });

            modelBuilder.Entity("HueFestival.Models.Loai_Ve", b =>
                {
                    b.Property<int>("IdLoai_ve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoai_ve"));

                    b.Property<string>("LoaiVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Loai_VeIdLoai_ve")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLoai_ve");

                    b.HasIndex("Loai_VeIdLoai_ve");

                    b.ToTable("Loai_Ves");
                });

            modelBuilder.Entity("HueFestival.Models.Nhom_CTr", b =>
                {
                    b.Property<int>("IdNhomCTr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhomCTr"));

                    b.Property<string>("TenNhom_CTr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNhomCTr");

                    b.ToTable("Nhom_CTrs");
                });

            modelBuilder.Entity("HueFestival.Models.TinTuc", b =>
                {
                    b.Property<int>("IdTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTinTuc"));

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TuaDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTinTuc");

                    b.ToTable("TinTucs");
                });

            modelBuilder.Entity("HueFestival.Models.Ve", b =>
                {
                    b.Property<int>("IdVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVe"));

                    b.Property<int>("ChiTiet_CTrsIdChiTiet_Ctr")
                        .HasColumnType("int");

                    b.Property<int>("GiaVe")
                        .HasColumnType("int");

                    b.Property<int>("IdChiTiet_Ctr")
                        .HasColumnType("int");

                    b.Property<int>("IdLoai_ve")
                        .HasColumnType("int");

                    b.Property<int>("Loai_VesIdLoai_ve")
                        .HasColumnType("int");

                    b.Property<string>("MaVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayPhatHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SLg")
                        .HasColumnType("int");

                    b.HasKey("IdVe");

                    b.HasIndex("ChiTiet_CTrsIdChiTiet_Ctr");

                    b.HasIndex("Loai_VesIdLoai_ve");

                    b.ToTable("Ves");
                });

            modelBuilder.Entity("HueFestival.Models.ChiTiet_CTr", b =>
                {
                    b.HasOne("HueFestival.Models.ChuongTrinh", "ChuongTrinhs")
                        .WithMany("ChiTiet_CTrs")
                        .HasForeignKey("ChuongTrinhsIdCTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.DiaDiem", "DiaDiems")
                        .WithMany()
                        .HasForeignKey("DiaDiemsIdDiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.DoanNT", "DoanNTs")
                        .WithMany("ChiTiet_Ctrs")
                        .HasForeignKey("DoanNTsIdDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.Nhom_CTr", "Nhom_CTrs")
                        .WithMany("ChiTiet_CTrs")
                        .HasForeignKey("Nhom_CTrsIdNhomCTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhs");

                    b.Navigation("DiaDiems");

                    b.Navigation("DoanNTs");

                    b.Navigation("Nhom_CTrs");
                });

            modelBuilder.Entity("HueFestival.Models.DiaDiem", b =>
                {
                    b.HasOne("HueFestival.Models.LoaiDiaDiem", "LoaiDiaDiems")
                        .WithMany("DiaDiems")
                        .HasForeignKey("LoaiDiaDiemsIdLoaiDD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiDiaDiems");
                });

            modelBuilder.Entity("HueFestival.Models.HinhAnh_CTr", b =>
                {
                    b.HasOne("HueFestival.Models.ChuongTrinh", "ChuongTrinhs")
                        .WithMany("HinhAnh_CTrs")
                        .HasForeignKey("ChuongTrinhsIdCTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhs");
                });

            modelBuilder.Entity("HueFestival.Models.LoaiDiaDiem", b =>
                {
                    b.HasOne("HueFestival.Models.ChiTiet_CTr", "ChiTiet_CTrs")
                        .WithMany()
                        .HasForeignKey("ChiTiet_CTrsIdChiTiet_Ctr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTiet_CTrs");
                });

            modelBuilder.Entity("HueFestival.Models.Loai_Ve", b =>
                {
                    b.HasOne("HueFestival.Models.Loai_Ve", null)
                        .WithMany("Loai_Ves")
                        .HasForeignKey("Loai_VeIdLoai_ve");
                });

            modelBuilder.Entity("HueFestival.Models.Ve", b =>
                {
                    b.HasOne("HueFestival.Models.ChiTiet_CTr", "ChiTiet_CTrs")
                        .WithMany("Ves")
                        .HasForeignKey("ChiTiet_CTrsIdChiTiet_Ctr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.Loai_Ve", "Loai_Ves")
                        .WithMany()
                        .HasForeignKey("Loai_VesIdLoai_ve")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTiet_CTrs");

                    b.Navigation("Loai_Ves");
                });

            modelBuilder.Entity("HueFestival.Models.ChiTiet_CTr", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("HueFestival.Models.ChuongTrinh", b =>
                {
                    b.Navigation("ChiTiet_CTrs");

                    b.Navigation("HinhAnh_CTrs");
                });

            modelBuilder.Entity("HueFestival.Models.DoanNT", b =>
                {
                    b.Navigation("ChiTiet_Ctrs");
                });

            modelBuilder.Entity("HueFestival.Models.LoaiDiaDiem", b =>
                {
                    b.Navigation("DiaDiems");
                });

            modelBuilder.Entity("HueFestival.Models.Loai_Ve", b =>
                {
                    b.Navigation("Loai_Ves");
                });

            modelBuilder.Entity("HueFestival.Models.Nhom_CTr", b =>
                {
                    b.Navigation("ChiTiet_CTrs");
                });
#pragma warning restore 612, 618
        }
    }
}
