// <auto-generated />
using System;
using HueFestival.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HueFestival.Migrations
{
    [DbContext(typeof(HueFestival_DbContext))]
    partial class HueFestival_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HueFestival.Models.Account", b =>
                {
                    b.Property<int>("IdAcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAcc"));

                    b.Property<int>("ChucVusIdChucVu")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdAcc");

                    b.HasIndex("ChucVusIdChucVu");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("HueFestival.Models.Check_in", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChucNangsIdchucNang")
                        .HasColumnType("int");

                    b.Property<int>("ChucVusIdChucVu")
                        .HasColumnType("int");

                    b.Property<int>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCheckIn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChucNangsIdchucNang");

                    b.HasIndex("ChucVusIdChucVu");

                    b.ToTable("Check_in");
                });

            modelBuilder.Entity("HueFestival.Models.ChiTiet_CTr", b =>
                {
                    b.Property<int>("IdChiTiet_Ctr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChiTiet_Ctr"));

                    b.Property<int>("ChuongTrinhsIdCTr")
                        .HasColumnType("int");

                    b.Property<int>("DiaDiemsIdDiaDiem")
                        .HasColumnType("int");

                    b.Property<int>("DoanNTsIdDoan")
                        .HasColumnType("int");

                    b.Property<int>("IdCtr")
                        .HasColumnType("int");

                    b.Property<int>("IdDiaDiem")
                        .HasColumnType("int");

                    b.Property<int?>("IdDoan")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("IdNhomCTr")
                        .HasColumnType("int");

                    b.Property<int>("Nhom_CTrsIdNhomCTr")
                        .HasColumnType("int");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<DateTime>("fDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("tDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdChiTiet_Ctr");

                    b.HasIndex("ChuongTrinhsIdCTr");

                    b.HasIndex("DiaDiemsIdDiaDiem");

                    b.HasIndex("DoanNTsIdDoan");

                    b.HasIndex("Nhom_CTrsIdNhomCTr");

                    b.ToTable("ChiTiet_CTr");
                });

            modelBuilder.Entity("HueFestival.Models.ChiTiet_DatVe", b =>
                {
                    b.Property<int>("IdDatVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDatVe"));

                    b.Property<int>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("IdVe")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangsIdKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SLgVe")
                        .HasColumnType("int");

                    b.Property<int>("ThongTin_VesIdVe")
                        .HasColumnType("int");

                    b.HasKey("IdDatVe");

                    b.HasIndex("KhachHangsIdKhachHang");

                    b.HasIndex("ThongTin_VesIdVe");

                    b.ToTable("ChiTiet_DatVe");
                });

            modelBuilder.Entity("HueFestival.Models.ChucNang", b =>
                {
                    b.Property<int>("IdchucNang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdchucNang"));

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdchucNang");

                    b.ToTable("ChucNang");
                });

            modelBuilder.Entity("HueFestival.Models.ChucVu", b =>
                {
                    b.Property<int>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChucVu"));

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("HueFestival.Models.ChuongTrinh", b =>
                {
                    b.Property<int>("IdCTr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCTr"));

                    b.Property<int>("Arrange")
                        .HasColumnType("int");

                    b.Property<double>("GiaTien")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCtr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeInOff")
                        .HasColumnType("int");

                    b.HasKey("IdCTr");

                    b.ToTable("ChuongTrinh");
                });

            modelBuilder.Entity("HueFestival.Models.DiaDiem", b =>
                {
                    b.Property<int>("IdDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiaDiem"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLoaiDD")
                        .HasColumnType("int");

                    b.Property<int>("LoaiDiaDiemsIdLoai_DD")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("ToaDoX")
                        .HasColumnType("float");

                    b.Property<double?>("ToaDoY")
                        .HasColumnType("float");

                    b.HasKey("IdDiaDiem");

                    b.HasIndex("LoaiDiaDiemsIdLoai_DD");

                    b.ToTable("DiaDiem");
                });

            modelBuilder.Entity("HueFestival.Models.DoanNT", b =>
                {
                    b.Property<int>("IdDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDoan"));

                    b.Property<string>("TenDoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDoan");

                    b.ToTable("DoanNT");
                });

            modelBuilder.Entity("HueFestival.Models.HinhAnh_CTr", b =>
                {
                    b.Property<int>("IdHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHinhAnh"));

                    b.Property<int>("ChuongTrinhsIdCTr")
                        .HasColumnType("int");

                    b.Property<int>("IdCtr")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHinhAnh");

                    b.HasIndex("ChuongTrinhsIdCTr");

                    b.ToTable("HinhAnh_CTr");
                });

            modelBuilder.Entity("HueFestival.Models.HoTro", b =>
                {
                    b.Property<int>("IdHoTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoTro"));

                    b.Property<string>("HoTroName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHoTro");

                    b.ToTable("HoTro");
                });

            modelBuilder.Entity("HueFestival.Models.KhachHang", b =>
                {
                    b.Property<int>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhachHang"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("HueFestival.Models.Loai_DiaDiem", b =>
                {
                    b.Property<int>("IdLoai_DD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoai_DD"));

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuaDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLoai_DD");

                    b.ToTable("Loai_DiaDiem");
                });

            modelBuilder.Entity("HueFestival.Models.Loai_Ve", b =>
                {
                    b.Property<int>("IdLoai_ve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoai_ve"));

                    b.Property<string>("LoaiVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Loai_VeIdLoai_ve")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLoai_ve");

                    b.HasIndex("Loai_VeIdLoai_ve");

                    b.ToTable("Loai_Ve");
                });

            modelBuilder.Entity("HueFestival.Models.Nhom_CTr", b =>
                {
                    b.Property<int>("IdNhomCTr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhomCTr"));

                    b.Property<string>("TenNhom_CTr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNhomCTr");

                    b.ToTable("Nhom_CTr");
                });

            modelBuilder.Entity("HueFestival.Models.QuyenHanh", b =>
                {
                    b.Property<int>("IdQuyenHanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuyenHanh"));

                    b.Property<int>("ChucNangsIdchucNang")
                        .HasColumnType("int");

                    b.Property<int>("ChucVusIdChucVu")
                        .HasColumnType("int");

                    b.Property<int>("IdChucNang")
                        .HasColumnType("int");

                    b.Property<int>("IdChucVu")
                        .HasColumnType("int");

                    b.HasKey("IdQuyenHanh");

                    b.HasIndex("ChucNangsIdchucNang");

                    b.HasIndex("ChucVusIdChucVu");

                    b.ToTable("QuyenHanh");
                });

            modelBuilder.Entity("HueFestival.Models.ThongTin_Ve", b =>
                {
                    b.Property<int>("IdVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVe"));

                    b.Property<int>("ChuongTrinhsIdCTr")
                        .HasColumnType("int");

                    b.Property<int>("GiaVe")
                        .HasColumnType("int");

                    b.Property<int>("IdChuongTrinh")
                        .HasColumnType("int");

                    b.Property<int>("IdLoai_ve")
                        .HasColumnType("int");

                    b.Property<int>("Loai_VesIdLoai_ve")
                        .HasColumnType("int");

                    b.Property<string>("MaVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayPhatHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SLg")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdVe");

                    b.HasIndex("ChuongTrinhsIdCTr");

                    b.HasIndex("Loai_VesIdLoai_ve");

                    b.ToTable("ThongTin_Ve");
                });

            modelBuilder.Entity("HueFestival.Models.TinTuc", b =>
                {
                    b.Property<int>("IdTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTinTuc"));

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TuaDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTinTuc");

                    b.ToTable("TinTuc");
                });

            modelBuilder.Entity("HueFestival.Models.Account", b =>
                {
                    b.HasOne("HueFestival.Models.ChucVu", "ChucVus")
                        .WithMany("Accounts")
                        .HasForeignKey("ChucVusIdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVus");
                });

            modelBuilder.Entity("HueFestival.Models.Check_in", b =>
                {
                    b.HasOne("HueFestival.Models.ChucNang", "ChucNangs")
                        .WithMany()
                        .HasForeignKey("ChucNangsIdchucNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.ChucVu", "ChucVus")
                        .WithMany()
                        .HasForeignKey("ChucVusIdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucNangs");

                    b.Navigation("ChucVus");
                });

            modelBuilder.Entity("HueFestival.Models.ChiTiet_CTr", b =>
                {
                    b.HasOne("HueFestival.Models.ChuongTrinh", "ChuongTrinhs")
                        .WithMany("ChiTiet_CTrs")
                        .HasForeignKey("ChuongTrinhsIdCTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.DiaDiem", "DiaDiems")
                        .WithMany("ChiTiet_CTrs")
                        .HasForeignKey("DiaDiemsIdDiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.DoanNT", "DoanNTs")
                        .WithMany("ChiTiet_Ctrs")
                        .HasForeignKey("DoanNTsIdDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.Nhom_CTr", "Nhom_CTrs")
                        .WithMany("ChiTiet_CTrs")
                        .HasForeignKey("Nhom_CTrsIdNhomCTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhs");

                    b.Navigation("DiaDiems");

                    b.Navigation("DoanNTs");

                    b.Navigation("Nhom_CTrs");
                });

            modelBuilder.Entity("HueFestival.Models.ChiTiet_DatVe", b =>
                {
                    b.HasOne("HueFestival.Models.KhachHang", "KhachHangs")
                        .WithMany("ChiTiet_DatVes")
                        .HasForeignKey("KhachHangsIdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.ThongTin_Ve", "ThongTin_Ves")
                        .WithMany()
                        .HasForeignKey("ThongTin_VesIdVe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHangs");

                    b.Navigation("ThongTin_Ves");
                });

            modelBuilder.Entity("HueFestival.Models.DiaDiem", b =>
                {
                    b.HasOne("HueFestival.Models.Loai_DiaDiem", "LoaiDiaDiems")
                        .WithMany("DiaDiems")
                        .HasForeignKey("LoaiDiaDiemsIdLoai_DD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiDiaDiems");
                });

            modelBuilder.Entity("HueFestival.Models.HinhAnh_CTr", b =>
                {
                    b.HasOne("HueFestival.Models.ChuongTrinh", "ChuongTrinhs")
                        .WithMany("HinhAnh_CTrs")
                        .HasForeignKey("ChuongTrinhsIdCTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhs");
                });

            modelBuilder.Entity("HueFestival.Models.Loai_Ve", b =>
                {
                    b.HasOne("HueFestival.Models.Loai_Ve", null)
                        .WithMany("Loai_Ves")
                        .HasForeignKey("Loai_VeIdLoai_ve");
                });

            modelBuilder.Entity("HueFestival.Models.QuyenHanh", b =>
                {
                    b.HasOne("HueFestival.Models.ChucNang", "ChucNangs")
                        .WithMany("QuyenHanhs")
                        .HasForeignKey("ChucNangsIdchucNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.ChucVu", "ChucVus")
                        .WithMany("QuyenHanhs")
                        .HasForeignKey("ChucVusIdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucNangs");

                    b.Navigation("ChucVus");
                });

            modelBuilder.Entity("HueFestival.Models.ThongTin_Ve", b =>
                {
                    b.HasOne("HueFestival.Models.ChuongTrinh", "ChuongTrinhs")
                        .WithMany("ThongTin_Ve")
                        .HasForeignKey("ChuongTrinhsIdCTr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HueFestival.Models.Loai_Ve", "Loai_Ves")
                        .WithMany()
                        .HasForeignKey("Loai_VesIdLoai_ve")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhs");

                    b.Navigation("Loai_Ves");
                });

            modelBuilder.Entity("HueFestival.Models.ChucNang", b =>
                {
                    b.Navigation("QuyenHanhs");
                });

            modelBuilder.Entity("HueFestival.Models.ChucVu", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("QuyenHanhs");
                });

            modelBuilder.Entity("HueFestival.Models.ChuongTrinh", b =>
                {
                    b.Navigation("ChiTiet_CTrs");

                    b.Navigation("HinhAnh_CTrs");

                    b.Navigation("ThongTin_Ve");
                });

            modelBuilder.Entity("HueFestival.Models.DiaDiem", b =>
                {
                    b.Navigation("ChiTiet_CTrs");
                });

            modelBuilder.Entity("HueFestival.Models.DoanNT", b =>
                {
                    b.Navigation("ChiTiet_Ctrs");
                });

            modelBuilder.Entity("HueFestival.Models.KhachHang", b =>
                {
                    b.Navigation("ChiTiet_DatVes");
                });

            modelBuilder.Entity("HueFestival.Models.Loai_DiaDiem", b =>
                {
                    b.Navigation("DiaDiems");
                });

            modelBuilder.Entity("HueFestival.Models.Loai_Ve", b =>
                {
                    b.Navigation("Loai_Ves");
                });

            modelBuilder.Entity("HueFestival.Models.Nhom_CTr", b =>
                {
                    b.Navigation("ChiTiet_CTrs");
                });
#pragma warning restore 612, 618
        }
    }
}
